### ISSUE TITLE
After verify API token, a prompt says 'SyntaxError:Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jun14** [grantwinney/pinboard-bookmarks-to-chrome#28]
thx for offering such a nice tool.
but after I verified my token, a prompt says 'SyntaxError:Unexpected token < in JSON at position 0'
I don't know what is going wrong.

![wx20170516-104617](https://cloud.githubusercontent.com/assets/4515694/26087741/1da2c8ca-3a25-11e7-9fd1-03b727d36d29.png)

please help.

**Comment by grantwinney** [comment]
Hm, it wasn't doing that a couple weeks ago when I last used it. But now I'm getting the same error. 

I'll check it out and see what's going on.

**Comment by grantwinney** [comment]
When hitting the Pinboard API to verify the API token, it gets an error page back instead of the valid JSON it expects. The extension tries to parse it, which fails.

The API url is https://api.pinboard.in/v1/ but trying to open that page is throwing a "403 forbidden" response code. That may be normal however.

Nothing on the Pinboard Twitter page suggests there's an issue, and the https://status.pinboard.in url is either down or just doesn't exist. That's a bummer. I sent an email to support@pinboard.in.

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<link rel="stylesheet" href="/stylesheets/main.css?v=a33a" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Pinboard is Down</title>

</head>
<body id="pinboard">

<div id="banner">
  <div id="logo">
  <img src="/bluepin.gif" style="margin-right:2px;"/>
  <a style="font-size:18px" href="/">Pinboard</a>
  
  
   <div id="timer"></div>
  </div>

  <div id="top_menu">
 ...
  </div>
    <div style="clear:both"></div>

</div>
<div style="height:700px;">
<h1>Pinboard is Down</h1>


<br/>

<img src="/images/ali_knockout.jpg" />
<br/>
<p>But it cannot be kept down.
<p>Please check <a href="http://twitter.com/Pinboard/">the site Twitter account (@Pinboard)</a> and <a href="http://status.pinboard.in/">status page</a> for the latest status updates.</p>

<br/>
<div style="clear:both"></div>
</div>

<div id="footer">
&copy; Nine Fives Software.  Problems or questions?  Contact &lt;<b>support@pinboard.in</b>&gt;.
<br/>
</div>


  <div style="clear:both"></div>
  </div>
</body>

</html>
```

**Comment by grantwinney** [comment]
@jun14 I have not heard back from Pinboard yet, but I just tried again and the extension is able to validate my API token now.

Could you try again and see if you get further?

---

(Oddly, the http://status.pinboard.in/ site is still unavailable, or never was available, and nothing on his Twitter page indicates a hiccup in service. It was just down for awhile and now appears to be back up.)

**Comment by jun14** [comment]
![image](https://cloud.githubusercontent.com/assets/4515694/26184272/737dbcb8-3bb6-11e7-88e4-096c1912d1a7.png)
Sounds like a bug caused  by pinboard itself. 
Anyway the tool you offer works fine now!  Thanks
