### ISSUE TITLE
Problems finding the "Bookmarks Bar"

### ISSUE THREAD

**Issue by marcosmesser** [grantwinney/pinboard-bookmarks-to-chrome#29]
I had trouble syncing my bookmarks, because the extension didn't found the Bookmarks Bar.

Initially, Chrome wasn't in English, but even after changing it, the error persisted.

It turns out that in my browser (Version 58.0.3029.110 (Official Build) (64-bit)), the 'b' in bar was lower cased.

It worked after changing [line 517](https://github.com/grantwinney/pinboard-bookmarks-to-chrome/blob/master/scripts/options.js#L517) to
`if (children[i].title == 'Bookmarks bar') {`

**Comment by grantwinney** [comment]
Thanks for tracking that down @marcosmesser! I changed the comparison to be case-insensitive, so hopefully it works okay for you now.

Out of curiosity (if you don't mind), what system do you have Chrome running on? I just tried it on Mac (same Chrome version) and it worked without the fix - haven't tried it on Windows for some time...

**Comment by marcosmesser** [comment]
Windows 10 (latest version).

**Comment by grantwinney** [comment]
Thanks. Good to know. Had only tested it on Win7.

**Comment by grantwinney** [comment]
Gonna close this one, but please shoot me a message if you find it's still an issue.
