### ISSUE TITLE
Bookmarks are not sorted

### ISSUE THREAD

**Issue by diskostu** [grantwinney/pinboard-bookmarks-to-chrome#32]
The folders are sorted, but not the bookmarks inside.

![image](https://user-images.githubusercontent.com/574147/52860016-959f1c00-312e-11e9-98ea-2ef97be6dc42.png)

**Comment by diskostu** [comment]
Just to make sure. Should the bookmarks be already sorted (bug) or is this not yet implemented (feature)? I'm not a JavaScript guy, so I cannot see immediately which case is true.

**Comment by grantwinney** [comment]
I'd consider it a bug @diskostu.

**Comment by diskostu** [comment]
Okay. Maybe I'll have a look into it.
