### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by berot3** [grantwinney/pinboard-bookmarks-to-chrome#33]
Any plans for porting this to Firefox?

Or is there maybe something else exactly like this but for firerfox?

Thanks!

**Comment by grantwinney** [comment]
I don't use Firefox, and I haven't used Pinboard in a couple years (so I can't even test it), so no plans to port this anytime soon.

There shouldn't be too much work to do it though... maybe changing the name of the bookmarks bar in [options.js](https://github.com/grantwinney/pinboard-bookmarks-to-chrome/blob/master/scripts/options.js). If you feel inclined to test it out and do a PR, I can merge it and submit it to the Firefox store.

I gave it an MIT license, so you can feel free to modify it and release it to the Firefox store yourself if you'd like to give it a try.

**Comment by berot3** [comment]
Thanks for the quick reply!

How about getting a bit off-topic? 😄

- - -

May I ask what the reason are for not using pinboard anymore and what you use instead?

I am also not 100% happy with pinboard, but I like that it’s social and open!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by grantwinney** [comment]
@berot3 It became just another place where things collected dust, lol! I had thousands of bookmarks in there at one point, but I could rarely find exactly what I was looking for.

I like using wiki's too, and I use a hosted Confluence instance for personal notes and record-keeping and stuff, so I ended up moving some of the bookmarks in there that I wanted to remember, under appropriate "pages", and figured I'd just Google the rest if I ever needed to find them again. 😏 

I haven't found another service like Pinboard, but then I haven't really looked. 🤷‍♂ Out of curiosity, what makes you not like it? Missing features?
